#!/usr/bin/bash

function install-fonts() {
  font_dir=$HOME/.local/share/fonts
  fonts=( "KisMiklos.otf" "OpenMoji-color-colr1_svg.ttf" )

  [[ -d "$font_dir" ]] || mkdir "$font_dir"  # Create user-font dir unless it exits

  # Copy in missing, required fonts
  for font in ${fonts[@]}
  do
    [[ -r "$font_dir/$font" ]] || tar -xf fonts.txz -C "$font_dir" "$font"
  done

  fc-cache -r  # Reload the installed fonts
}

function install-config() {
  config_dir=$HOME/.local/etc/xdg/dunst

  [[ -d "$config_dir" ]] || mkdir -pv "$config_dir"            # Create user-dunst config-dir
  [[ -r "$config_dir/dunstrc" ]] || cp dunstrc "$config_dir"/  # Copy in dunstrc

  # Restart dunst, without poluting console, detached so you can close the window
  pkill dunst
  dunst &>/dev/null &
  disown
}

# Run the functions
install-fonts
install-config
